clone:
  git:
    image: plugins/git

pipeline:
  deploy-dev:
    image: appleboy/drone-ssh
    host: journals
    username: ubuntu
    secrets: [ssh_key]
    command_timeout: 300
    when:
      branch: dev
      status: success
    script:
      - cd frontend/admin
      - git checkout -- package-lock.json
      - git checkout dev
      - git pull origin dev
      - export NVM_DIR="$HOME/.nvm"
      - source $NVM_DIR/nvm.sh
      - nvm use stable
      - npm i
      - CI=true node scripts/test.js --env=jsdom
      - npm run build
      - pm2 restart journals-frontend-admin --update-env

  deploy-master:
    image: appleboy/drone-ssh
    host: journals
    port: 22
    username: ubuntu
    secrets: [ssh_key]
    command_timeout: 300
    when:
      branch: master
      status: success
    script:
      - cd frontend/admin
      - git checkout master
      - git pull origin master
      - export NVM_DIR="$HOME/.nvm"
      - source $NVM_DIR/nvm.sh
      - nvm use stable
      - npm i
      - npm run build
      - pm2 restart journals-frontend-admin --update-env
