export const LOGIN = 'LOGIN';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const LOGOUT = 'LOGOUT';
export const FETCH_CONTROLLED_USER = 'FETCH_CONTROLLED_USER';
export const SET_CONTROLLED_USER = 'SET_CONTROLLED_USER';
export const RESET_CONTROLLED_USER = 'RESET_CONTROLLED_USER';
