export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const CREATE_ARTICLE_TAG = 'CREATE_ARTICLE_TAG';
export const REMOVE_ARTICLE_TAG = 'REMOVE_ARTICLE_TAG';
